export { default as OpenSvg } from './OpenSvg'
export { default as CloseSvg } from './CloseSvg'
export { default as XSvg } from './XSvg'
export { default as LocationSvg } from './LocationSvg'
export { default as BedSvg } from './BedSvg'
export { default as AreaSvg } from './AreaSvg'
export { default as ZipCodeSvg } from './ZipCodeSvg'
